# Generated by Django 3.1.3 on 2020-11-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('apellidos', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45, null=True)),
                ('anyo', models.IntegerField(null=True)),
                ('URL', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id_revista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Com_con',
            fields=[
                ('congreso', models.CharField(max_length=45, null=True)),
                ('edicion', models.CharField(max_length=45, null=True)),
                ('lugar', models.CharField(max_length=45, null=True)),
                ('pagina_inicio', models.IntegerField(null=True)),
                ('pagina_fin', models.IntegerField(null=True)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bbdd.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('editorial', models.CharField(max_length=45, null=True)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bbdd.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbdd.persona')),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbdd.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id_ejemplar', models.IntegerField(primary_key=True, serialize=False)),
                ('volumen', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbdd.revista')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('pagina_inicio', models.IntegerField(null=True)),
                ('pagina_fin', models.IntegerField(null=True)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bbdd.publicacion')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbdd.ejemplar')),
            ],
        ),
    ]
